# Custom Language File for Launcher Customizer

[ejs.app]
title = "Dreadful Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/imnowaa/DreadfulLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/imnowaa/DreadfulLauncher"
supportLink = "https://github.com/imnowaa/DreadfulLauncher/issues"

[ejs.welcome]
welcomeHeader = "ENTRÉE AUX ENFERS EN COURS..."
welcomeDescription = "THE MOON IS WATCHING"
welcomeDescCTA = "Vous y êtes presques..."
