# Custom Language File for Launcher Customizer

[ejs.app]
title = "Noe Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/imnowaa/NoeLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/imnowaa/NoeLauncher"
supportLink = "https://github.com/imnowaa/NoeLauncher/issues"

[ejs.welcome]
welcomeHeader = "RESTAURATION DE VOTRE SAUVEGARDE"
welcomeDescription = "Êtes-vous prêt à clore ce chapitre ?"
welcomeDescCTA = "Vous y êtes presques..."
