[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUT MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essentiel"
newsButton = "ACTUALITÉS"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur sélectionné"
launchDetails = "Veuillez patienter.."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Vérification des actualités.."
newsErrorFailedSpan = "Échec du chargement des actualités"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Aucune actualité"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "EMAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublié ?"
loginRememberMeText = "se souvenir de moi ?"
loginButtonText = "CONNEXION"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d’un compte ?"
loginPasswordDisclaimer1 = "Votre mot de passe est envoyé directement à Mojang et n’est jamais stocké."
loginPasswordDisclaimer2 = "{appName} n’est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Connexion avec Microsoft"
loginWithMojang = "Connexion avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Sélectionner un compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "À propos"
navUpdates = "Mises à jour"
navDone = "Terminé"

tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajouter de nouveaux comptes ou gérer les comptes existants."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"

minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options liées au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein écran."
autoConnectTitle = "Connexion automatique au serveur au lancement."
launchDetachedTitle = "Lancer le jeu indépendamment du launcher."
launchDetachedDesc = "Si le jeu n'est pas détaché, fermer le launcher fermera aussi le jeu."

tabModsHeaderText = "Paramètres des mods"
tabModsHeaderDesc = "Activer ou désactiver les mods."
switchServerButton = "Changer"
requiredMods = "Mods obligatoires"
optionalMods = "Mods optionnels"
dropinMods = "Mods instantanés"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour rafraîchir)"
shaderpacks = "Packs de shaders"
shaderpackDesc = "Activer ou désactiver les shaders. Attention, les shaders nécessitent une configuration puissante. Vous pouvez ajouter des packs personnalisés ici."
selectShaderpack = "Sélectionner un shaderpack"

tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Gérer la configuration Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "RAM maximale"
minRAM = "RAM minimale"
memoryDesc = "La RAM minimale recommandée est de 3 Go. Définir des valeurs identiques pour min et max peut réduire les lags."
memoryTotalTitle = "Totale"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionner l'exécutable Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "L’exécutable Java est vérifié avant le lancement du jeu."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM supplémentaires"
jvmOptsDesc = "Options à fournir à la JVM à l’exécution. Ne pas inclure <em>-Xms</em> et <em>-Xmx</em>."

launcherTabHeaderText = "Paramètres du launcher"
launcherTabHeaderDesc = "Options liées au launcher lui-même."
allowPrereleaseTitle = "Autoriser les mises à jour préliminaires."
allowPrereleaseDesc = "Les préversions incluent de nouvelles fonctionnalités qui peuvent ne pas être entièrement testées ou intégrées.<br>Ceci est toujours vrai si vous utilisez une version préliminaire."

dataDirectoryTitle = "Répertoire de données"
selectDataDirectory = "Sélectionner le répertoire de données"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tous les fichiers du jeu et les installations Java locales seront stockés dans ce dossier.<br>Les captures d'écran et les mondes sont stockés dans le dossier de l’instance liée à la configuration du serveur."

aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Voir les informations et les notes de version actuelles."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Code source (GitHub)"
support = "Assistance"
devToolsConsole = "Console DevTools"
releaseNotes = "Notes de version"
changelog = "Journal des modifications"
noReleaseNotes = "Aucune note de version"
viewReleaseNotes = "Voir les notes de version sur GitHub"

launcherUpdatesHeaderText = "Mises à jour du launcher"
launcherUpdatesHeaderDesc = "Télécharger, installer et consulter les mises à jour du launcher."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Nouveautés"
updateReleaseNotes = "Notes de mise à jour"

[ejs.waiting]
waitingText = "En attente de Microsoft..."

[ejs.welcome]
continueButton = "CONTINUER"


[js.discord]
waiting = "En attente du client..."
state = "Serveur : {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "CONNEXION"
loggingIn = "CONNEXION EN COURS"
success = "RÉUSSI"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue lors de la connexion"
desc = "Une erreur inconnue est survenue. Veuillez consulter la console pour plus de détails."

[js.landing.launch]
pleaseWait = "Veuillez patienter..."
failureTitle = "Erreur lors du lancement"
failureText = "Voir la console (CTRL + Shift + i) pour plus de détails."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement..."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Vérification des infos système..."
noCompatibleJava = "Aucune installation<br>Java compatible trouvée"
installJavaMessage = "Pour lancer Minecraft, vous avez besoin d'une installation 64 bits de Java {major}. Souhaitez-vous que nous l'installions ?"
installJava = "Installer Java"
installJavaManually = "Installer manuellement"
javaDownloadPrepare = "Préparation du téléchargement de Java..."
javaDownloadFailureTitle = "Erreur lors du téléchargement de Java"
javaDownloadFailureText = "Voir la console (CTRL + Shift + i) pour plus de détails."
javaRequired = "Java requis<br>pour lancer"
javaRequiredMessage = '''Une installation valide de Java x64 {major} est requise.<br><br>Veuillez consulter notre <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">guide d'installation Java</a> pour les instructions.'''
javaRequiredDismiss = "J’ai compris"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Échec de la détection de la distribution OpenJDK."
javaDownloadCorruptedError = "Le JDK téléchargé est corrompu (hash incorrect)."
extractingJava = "Extraction de Java"
javaInstalled = "Java installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des infos serveur..."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Impossible de charger l’index de distribution. Voir la console (CTRL + Shift + i) pour plus de détails."
pleaseWait = "Veuillez patienter..."
errorDuringLaunchTitle = "Erreur lors du lancement"
seeConsoleForDetails = "Voir la console (CTRL + Shift + i) pour plus de détails."
validatingFileIntegrity = "Vérification de l’intégrité des fichiers..."
errorDuringFileVerificationTitle = "Erreur lors de la vérification des fichiers"
downloadingFiles = "Téléchargement des fichiers..."
errorDuringFileDownloadTitle = "Erreur lors du téléchargement des fichiers"
preparingToLaunch = "Préparation au lancement..."
launchingGame = "Lancement du jeu..."
launchWrapperNotDownloaded = "Le fichier principal, LaunchWrapper, n’a pas été téléchargé correctement. Le jeu ne peut pas démarrer.<br><br>Pour corriger cela, désactivez temporairement votre antivirus puis relancez.<br><br>Si possible, <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">signalez le problème</a> avec le nom de votre antivirus."
doneEnjoyServer = "C’est prêt. Bon jeu sur le serveur !"
checkConsoleForDetails = "Consultez la console (CTRL + Shift + i) pour plus de détails."

[js.landing.news]
checking = "Vérification des actualités"

[js.landing.discord]
loading = "Chargement du jeu..."
joining = "En route vers Westeros !"
joined = "Exploration du Royaume !"

[js.overlay]
dismiss = "Fermer"

[js.settings.fileSelectors]
executables = "Fichiers exécutables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Un problème est survenu"
errorMessage = "L’authentification Microsoft a échoué. Veuillez réessayer."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Un problème est survenu"
errorMessage = "La déconnexion Microsoft a échoué. Veuillez réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Sélectionner le compte"
selectedButton = "Compte sélectionné &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>Il s’agit de votre dernier compte"
lastAccountWarningMessage = "Vous devez être connecté à au moins un compte pour utiliser le launcher.<br><br>Souhaitez-vous vraiment vous déconnecter ?"
confirmButton = "Oui, je suis sûr"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d’utilisateur"
uuid = "UUID"
selectAccount = "Sélectionner un compte"
selectedAccount = "Compte sélectionné ✓"
logout = "Se déconnecter"

[js.settings.dropinMods]
removeButton = "Supprimer"
deleteFailedTitle = "Échec de suppression<br>du mod {fullName}"
deleteFailedMessage = "Assurez-vous que le fichier n’est pas utilisé, puis réessayez."
failedToggleTitle = "Échec d’activation/désactivation<br>d’un ou plusieurs mods"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Sélectionné : Java {version} ({vendor})"
invalidSelection = "Sélection invalide"
requiresJava = "Nécessite Java {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pré-version"
stableReleaseTitle = "Version stable"
releaseNotesFailed = "Échec du chargement des notes de version."

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
newPreReleaseTitle = "Nouvelle pré-version disponible"
downloadingButton = "Téléchargement..."
downloadButton = 'Télécharger depuis GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Fermez le launcher et exécutez le fichier pour mettre à jour.</span>'
latestVersionTitle = "Vous utilisez la dernière version"
checkForUpdatesButton = "Vérifier les mises à jour"
checkingForUpdatesButton = "Recherche de mises à jour..."

[js.settings.msftLogin]
errorTitle = "Échec de la connexion Microsoft"
errorMessage = "Impossible d’authentifier votre compte Microsoft. Veuillez réessayer."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale : Échec du chargement de l’index de distribution"
fatalErrorMessage = "Impossible d’établir une connexion avec nos serveurs pour télécharger l’index de distribution, et aucune copie locale n’est disponible.<br><br>L’index est essentiel pour récupérer les infos du serveur. Assurez-vous d’être connecté à Internet, puis relancez."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Échec de la mise à jour de la connexion"
failedMessage = "Échec de la mise à jour de la session pour <strong>{account}</strong>. Veuillez sélectionner un autre compte ou vous reconnecter."
failedMessageSelectAnotherAccount = "Veuillez vous reconnecter."
loginButton = "Connexion"
selectAnotherAccountButton = "Choisir un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Recherche de mise à jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Vérifier les mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Erreur lors de la connexion :<br>Profil non configuré"
noProfileDesc = "Votre compte Microsoft ne possède pas encore de profil Minecraft. Si vous venez d’acheter le jeu ou de l’activer via Xbox Game Pass, vous devez configurer votre profil sur <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Si vous ne possédez pas encore le jeu, vous pouvez également l’acheter sur <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Erreur lors de la connexion :<br>Pas de compte Xbox"
noXboxAccountDesc = "Votre compte Microsoft n’est associé à aucun compte Xbox."
xblBannedTitle = "Erreur lors de la connexion :<br>Xbox Live indisponible"
xblBannedDesc = "Votre compte Microsoft provient d’un pays où Xbox Live est indisponible ou banni."
under18Title = "Erreur lors de la connexion :<br>Autorisation parentale requise"
under18Desc = "Les comptes d’utilisateurs de moins de 18 ans doivent être ajoutés à une famille par un adulte."
unknownTitle = "Erreur inconnue lors de la connexion"
unknownDesc = "Une erreur inconnue s’est produite. Veuillez consulter la console pour plus de détails."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur interne :<br>Méthode non autorisée"
methodNotAllowedDesc = "Méthode non autorisée. Veuillez signaler cette erreur."
notFoundTitle = "Erreur interne :<br>Introuvable"
notFoundDesc = "Le point d’authentification est introuvable. Veuillez signaler ce problème."
accountMigratedTitle = "Erreur lors de la connexion :<br>Compte migré"
accountMigratedDesc = "Vous avez tenté de vous connecter avec un compte migré. Veuillez réessayer en utilisant votre adresse e-mail comme identifiant."
invalidCredentialsTitle = "Erreur lors de la connexion :<br>Identifiants incorrects"
invalidCredentialsDesc = "L’e-mail ou le mot de passe saisi est incorrect. Veuillez réessayer."
tooManyAttemptsTitle = "Erreur lors de la connexion :<br>Trop de tentatives"
tooManyAttemptsDesc = "Trop de tentatives de connexion ont été effectuées avec ce compte. Veuillez réessayer plus tard."
invalidTokenTitle = "Erreur lors de la connexion :<br>Jeton invalide"
invalidTokenDesc = "Le jeton d’accès fourni est invalide."
tokenHasProfileTitle = "Erreur lors de la connexion :<br>Jeton déjà lié à un profil"
tokenHasProfileDesc = "Le jeton d’accès possède déjà un profil. La sélection de profils n’est pas encore implémentée."
credentialsMissingTitle = "Erreur lors de la connexion :<br>Identifiants manquants"
credentialsMissingDesc = "Nom d'utilisateur ou mot de passe manquant, ou mot de passe trop court (moins de 3 caractères)."
invalidSaltVersionTitle = "Erreur lors de la connexion :<br>Version de sel invalide"
invalidSaltVersionDesc = "Version de sel invalide."
unsupportedMediaTypeTitle = "Erreur interne :<br>Type de média non supporté"
unsupportedMediaTypeDesc = "Type de média non pris en charge. Veuillez signaler cette erreur."
accountGoneTitle = "Erreur lors de la connexion :<br>Compte migré"
accountGoneDesc = "Ce compte a été migré vers un compte Microsoft. Veuillez vous connecter avec Microsoft."
unreachableTitle = "Erreur lors de la connexion :<br>Serveur injoignable"
unreachableDesc = "Impossible de contacter les serveurs d’authentification. Vérifiez votre connexion Internet et réessayez."
gameNotPurchasedTitle = "Erreur lors de la connexion :<br>Jeu non acheté"
gameNotPurchasedDesc = "Le compte utilisé n’a pas encore acheté Minecraft. Vous pouvez acheter le jeu sur <a href=\"https://minecraft.net/\">Minecraft.net</a>."
unknownErrorTitle = "Erreur inconnue lors de la connexion"
unknownErrorDesc = "Une erreur inconnue s’est produite. Veuillez consulter la console pour plus de détails."
